name: Python Code Quality
on: [push]
jobs:
  lock_file:
    runs-on: ubuntu-latest
    steps:
      - name: "Install UV"
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
      - run: uv lock â€”locked
  linting:
    runs-on: ubuntu-latest
    needs: [lock_file]
    steps:
      - name: "Install UV"
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
      - run: uvx run ruff check .
  formatting:
    runs-on: ubuntu-latest
    needs: [lock_file]
    steps:
      - name: "Install UV"
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
      - run: uvx run ruff format --check .
  type_consistency:
    runs-on: ubuntu-latest
    needs: [lock_file]
    steps:
      - name: "Install UV"
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
      - run: uv run pyright .
  tests:
    runs-on: ubuntu-latest
    needs: [lock_file]
    steps:
      - name: "Install UV"
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
      - run: uv run pytest -vv --durations=0 --cov
  build:
    runs-on: [ubuntu-latest]
    needs: [linting, formatting, type_consistency, tests]
    steps:
      - name: "Install UV"
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
      - run: uv run python -m build
